PROJECT:=Article

include makefile-latex/latex-std-dependence.mk
DEPS_MAIN_TEX:=${STYS_MINIMUS} ${CLSS_ARTICLE_ARGON}
DEPS_FIGS_TEX:=${STYS_MINIMUS} ${CLSS_STANDALONE_SILICON}

include makefile-latex/makefile-latex.mk
